#!/usr/bin/env node
/* writing.mjs — the Writing strand's sentences, chosen FROM THE CLASSICS so every one is a real sentence
   of a real book (never invented): dictation sentences, and model sentences for imitation, one set per
   shape (src/writing.js SHAPES). Only shipped passages, never one flagged needsReview. Writes
   app/src/data/writing.js; --check fails if it is stale. Deterministic: same texts, same choice. */
import { readFileSync, writeFileSync } from 'node:fs';
const ROOT = new URL('../../', import.meta.url);
const { SHAPES, sentences } = await import(new URL('app/src/writing.js', ROOT));
const { PASSAGES } = await import(new URL('app/src/data/library.js', ROOT));
const P = JSON.parse(readFileSync(new URL('app/src/data/passages.json', ROOT), 'utf8'));
const meta = Object.fromEntries(PASSAGES.map((p) => [p.id, p]));
const words = (s) => s.match(/[A-Za-z][A-Za-z'’-]*/g) || [];
const plain = (s) => !/[;:—–()[\]_*"“”‘]|--|\s'|'\s|^'/.test(s) && /^[A-Z]/.test(s) && /[.!?]$/.test(s) && !/\b(I|thee|thou|thy|ye)\b.*\b(thee|thou|thy|ye)\b/.test(s);
/* a dictation's band follows its LENGTH (a short sentence suits a six-year-old whatever book it is from) */
const lenBand = (n) => (n >= 4 && n <= 9 ? 1 : n >= 8 && n <= 15 ? 2 : n >= 12 && n <= 22 ? 3 : 0);
const dictation = [], models = Object.fromEntries(Object.keys(SHAPES).map((k) => [k, []]));
for (const p of P) {
  const m = meta[p.id]; if (!m || m.needsReview || p.kind === 'verse') continue;
  const ss = sentences(p.text.replace(/_/g, ''));
  const per = { 1: 0, 2: 0, 3: 0 };
  for (const s of ss) {
    const b = lenBand(words(s).length);
    if (b && b >= p.band - 1 && per[b] < 2 && plain(s)) { dictation.push({ id: `${p.id}-${dictation.filter((d) => d.passage === p.id).length}`, passage: p.id, work: p.work, band: b, text: s }); per[b]++; }
  }
}
/* models: real sentences of every shape, from the passages AND the full held texts of cleared works on
   the fable and children's shelves (a child imitates a sentence from a book they can open). */
const { WORKS } = await import(new URL('app/src/data/library.js', ROOT));
const { cleared } = await import(new URL('app/src/data/rights.js', ROOT));
const { existsSync } = await import('node:fs');
const sources = [...P.filter((p) => !meta[p.id]?.needsReview && p.kind !== 'verse').map((p) => ({ work: p.work, passage: p.id, text: p.text }))];
/* a hand-picked shelf of children's books (no editorial prefaces, no daggers), front matter skipped */
const MODEL_SHELF = ['aesop', 'justso', 'alice', 'lookingglass', 'wind', 'secretgarden', 'velveteen', 'peterrabbit', 'oz', 'happyprince', 'littlewomen', 'treasure', 'blackbeauty'];
for (const w of WORKS.filter((w) => MODEL_SHELF.includes(w.id) && w.held && cleared(w))) {
  const f = new URL(`app/public/texts/${w.id}.txt`, ROOT); if (!existsSync(f)) continue;
  const t = readFileSync(f, 'utf8'); sources.push({ work: w.id, passage: null, text: t.slice(Math.floor(t.length * 0.04)) });
}
const bandOf = (n) => (n <= 12 ? 1 : n <= 20 ? 2 : 3);
for (const src of sources) {
  const perWork = {};
  for (const s of sentences(src.text.replace(/_/g, ''))) for (const [k, S] of Object.entries(SHAPES)) {
    const w = words(s).length; if (w < 6 || w > 26 || !plain(s) || !S.test(s)) continue;
    if ((perWork[k] = (perWork[k] || 0)) >= 2 || models[k].length >= 18 || models[k].some((x) => x.text === s)) continue;
    perWork[k]++; models[k].push({ id: `${k}-${models[k].length}`, shape: k, passage: src.passage, work: src.work, band: bandOf(w), text: s });
  }
}
const out = '/* generated by tools/texts/writing.mjs from the held classics — never edit by hand */\nexport default ' + JSON.stringify({ dictation, models }, null, 1) + ';\n';
const path = new URL('app/src/data/writing.js', ROOT);
if (process.argv.includes('--check')) { if (readFileSync(path, 'utf8') !== out) { console.error('writing.js is stale: run node tools/texts/writing.mjs'); process.exit(1); } console.log('writing.js is up to date'); }
else { writeFileSync(path, out); console.log(`dictation ${dictation.length} (bands ${[1, 2, 3].map((b) => dictation.filter((d) => d.band === b).length).join('/')}), models ${Object.entries(models).map(([k, v]) => `${k} ${v.length}`).join(', ')}`); }
