"""The painting prompt for each of Bizzing English's 96 avatars, keyed by the id in
app/src/data/avatars.js (test/avatars.mjs checks the two lists agree)."""
AVATARS = {
    # 1 Fable Friends
    'tortoise': "A tortoise with a little red racing ribbon tied round its shell, smiling patiently.",
    'fieldmouse': "A tiny brown field mouse hugging an ear of golden wheat.",
    'hare': "A long-eared brown hare in little running shoes, mid-stride, with a cheeky grin.",
    'crow': "A glossy black crow dropping a pebble into a round clay water pitcher.",
    'ant': "A hard-working red ant carrying a grain of rice bigger than itself above its head.",
    'lion': "A gentle young lion with a big golden mane and a small white bandage on one front paw.",
    'grasshopper': "A bright green grasshopper happily playing a tiny wooden fiddle.",
    'goldengoose': "A white goose glowing with warm golden light, sitting proudly on a single shining golden egg.",
    # 2 Once Upon a Time
    'crownfrog': "A small green frog wearing a tiny gold crown, sitting on a lily pad.",
    'bearcub': "A round brown bear cub holding a blue bowl of porridge and a wooden spoon.",
    'bootcat': "A ginger cat in tall brown boots and a wide hat with a long feather, bowing politely.",
    'redhen': "A little red hen carrying a sheaf of wheat under one wing and a loaf of bread under the other.",
    'nightcapwolf': "A silly grey wolf wearing a frilly white nightcap and round spectacles, trying to look innocent.",
    'coachmouse': "A white mouse in a smart blue coachman's coat standing beside a small round orange pumpkin coach.",
    'stork': "A tall white stork with a red beak standing on one leg in a twiggy chimney-top nest.",
    'firebird': "A magnificent bird with flame-coloured feathers of red, orange and gold, its long tail glowing like embers.",
    # 3 Study Pets
    'bookworm': "A plump little green worm in round spectacles peeking out of a hole in a red book with a plain cover.",
    'candlemoth': "A soft fuzzy cream-coloured moth with feathery antennae fluttering beside a small candle flame.",
    'inkbeetle': "A shiny blue-black beetle whose round shell looks like a glass inkwell, with feathery quill antennae.",
    'dormouse': "A sleepy golden dormouse curled up asleep inside a china teacup with a blue pattern.",
    'bulldog': "A stout bulldog in a burgundy velvet smoking jacket, sitting very still like a bookend.",
    'cheshire': "A purple-and-pink striped cat with an enormous wide grin, its tail fading into thin air.",
    'marchhare': "A wild-eyed brown hare in a tall green top hat, holding a teapot.",
    'toad': "A grand green toad in a long motoring coat, round goggles pushed up on his head, gripping a steering wheel.",
    # 4 Baker Street
    'terrier': "A scruffy little wire-haired terrier in a tiny checked deerstalker cap, nose to the ground.",
    'pigeon': "A grey city pigeon with a tiny rolled-up note tied to its leg with a red ribbon.",
    'magnicat': "A tabby cat peering through a large brass magnifying glass, one eye hugely enlarged.",
    'moorhound': "A big shaggy grey hound with gentle glowing amber eyes, sitting in purple heather.",
    'keyraven': "A glossy black raven with a clear beak, bright friendly eyes and visible wings and feet, holding a small ornate brass key in its beak, standing.",
    'fiddleferret': "A sleek cream ferret playing a violin with great concentration, eyes closed.",
    'badger': "A wise old badger in a plaid dressing gown and slippers, carrying a lit lantern.",
    'mole': "A small velvety black mole in a straw boater hat, sitting in a little wooden rowing boat.",
    # 5 The Players
    'raccoon': "A raccoon holding a white theatre mask up beside its own masked face, peeking from a red curtain.",
    'pug': "A pug in a red-and-yellow jester's cap with little bells, grinning.",
    'donkey': "A cheerful grey donkey wearing a crown of pink roses and ivy leaves.",
    'shylion': "A shy little lion cub wearing a woolly yellow stage-costume mane that is far too big for it.",
    'turkey': "A proud bronze turkey wearing a big white ruffled Elizabethan collar.",
    'lanterndog': "A small scruffy white dog carrying a lantern in its mouth, a thornbush beside it, under a crescent moon.",
    'stag': "A noble red stag with antlers hung with little ribbons and a crown of oak leaves.",
    'bear': "A big friendly brown bear up on its hind legs in a playful leaping chase, snowflakes swirling around it.",
    # 6 Storm and Spell
    'gull': "A seagull wearing a blue sailor's neckerchief, standing on a wooden barrel.",
    'crab': "A small orange crab proudly holding up a single shining pearl in one claw.",
    'parrot': "A green parrot in a tiny captain's hat perched on a broken ship's mast.",
    'petrel': "A small round sooty-brown seabird with a white patch on its rump, a little hooked black beak and bright eyes, skimming low over a small cresting blue wave, wings spread.",
    'greycat': "A smoky grey cat with bright green eyes sitting beside a small bubbling black cauldron.",
    'jeweltoad': "A plump brown toad with a precious glowing ruby set in its forehead, looking dignified.",
    'flyingfish': "A silver flying fish leaping with its wing-like fins spread, sea spray sparkling around it.",
    'lark': "A small brown skylark singing at dawn, streams of golden light rising from its open beak.",
    # 7 The Orators
    'dove': "A white dove holding a sprig of olive leaves in its beak.",
    'parakeet': "A little green parakeet standing on a tiny marble podium, chest puffed out, one wing raised as if making a speech.",
    'eagle': "A proud eagle with a WHITE feathered head, a big hooked YELLOW beak, a dark brown body and yellow talons (a bald-eagle look, nothing like an owl), wearing a green laurel wreath, holding a rolled-up blank scroll.",
    'goose': "A white goose with a bronze collar honking an alarm, wings spread wide.",
    'wolf': "A grey she-wolf with a kind face sitting proudly on pale marble steps.",
    'elephant': "A grey elephant wearing a draped white toga with a purple border, trunk raised as if making a grand point.",
    'bull': "A strong white bull with garlands of flowers looped around its horns.",
    'lyrebird': "A lyrebird with a magnificent golden tail fanned up into the curved shape of a lyre, singing.",
    # 8 Debate Club
    'magpie': "A black-and-white magpie with a shimmering blue tail, beak open mid-sentence, very chatty.",
    'seal': "A grey seal clapping its flippers together in applause.",
    'howler': "A reddish howler monkey cupping a paw beside its mouth to call out.",
    'woodpecker': "A red-capped woodpecker tapping a small wooden gavel on a block.",
    'goat': "A little white goat standing on a wooden soapbox, mid-bleat, making its point.",
    'mynah': "A glossy black mynah bird with a bright yellow face patch and beak, mid-speech.",
    'orangutan': "An orange orangutan with a pondering expression, one finger raised, holding a closed book with a plain cover.",
    'cockatoo': "A great white cockatoo with its yellow crest fanned up like a glowing crown.",
    # 9 Illuminated Beasts
    'scribecat': "A small black-and-white cat curled up on a stack of blank parchment beside a feather quill.",
    'armoursnail': "A snail wearing a little silver knight's helmet on top of its spiral shell, very brave.",
    'swordrabbit': "A white rabbit holding a tiny wooden sword, fierce but adorable, painted like a creature from a medieval manuscript margin.",
    'trumpethare': "A hare blowing a long golden trumpet, in the flat bright colours of a medieval painting.",
    'wyvern': "A small green two-legged wyvern with bat wings, curled round a pot of ink.",
    'pelican': "A pelican with its chicks in a nest, painted like a medieval emblem in gold and lapis blue.",
    'islandwhale': "A friendly blue whale-like sea beast with a tiny green island and a palm tree on its back, like a medieval map creature.",
    'ouroboros': "A golden dragon curled into a perfect circle holding its own tail in its mouth, scales of shining gold leaf.",
    # 10 Word Beasts
    'inkpup': "A puppy made of soft ink-black fluff with one white ear, leaving little inky paw prints.",
    'porcupine': "A round porcupine whose quills are white feather writing quills with ink-dipped tips.",
    'hodge': "A plump tabby cat sitting on top of a huge closed book with a plain brown cover, looking very pleased.",
    'chauntecleer': "A splendid medieval rooster with a coral-red comb and feathers like burnished gold, crowing at sunrise.",
    'pressbeetle': "A stag beetle whose body is shaped like an old wooden printing press, a little ink on its horns.",
    'snark': "A strange friendly creature, half sea-creature and half feathered bird, with a puzzled face, from a nonsense poem.",
    'bandersnatch': "A fast, fluffy, frumious creature with a long neck and snapping jaws, comical not scary, in purple and orange fur.",
    'jabberwock': "A gangly whimsical dragon with flaming orange eyes, a long neck, a buttoned waistcoat and leathery wings, comical and kindly.",
    # 11 Romantic Wildlife
    'lamb': "A soft white lamb with a curly fleece and a little brass bell on a ribbon.",
    'robin': "A round robin redbreast perched on the handle of a garden fork.",
    'heron': "A grey heron standing tall and still among green reeds.",
    'cricket': "A cheerful brown cricket insect with long antennae, six legs and big folded back legs, chirping on a small flat grey hearthstone beside a tiny glowing ember.",
    'vole': "A small brown water vole sitting on a lily pad, whiskers twitching.",
    'albatross': "A great white albatross with enormous long wings gliding over the sea.",
    'kingfisher': "A brilliant blue and orange kingfisher diving with a little silver fish in its beak.",
    'tyger': "A majestic tiger cub whose black stripes glow at the edges like embers, eyes bright, standing proudly.",
    # 12 Mist and Mountain
    'dipper': "A small round brown-and-white dipper bird bobbing on a mossy stone in a stream.",
    'herdwick': "A mountain sheep with a white face and a thick grey fleece, standing on a rock.",
    'highlandcow': "A highland cow with long shaggy ginger hair falling over its eyes and wide curved horns.",
    'trout': "A speckled brown trout leaping out of the water with droplets flying.",
    'osprey': "An osprey with spread wings carrying a twig to its nest.",
    'dragonfly': "A shimmering blue dragonfly with lacy wings hovering above a lily.",
    'mountainhare': "A mountain hare changing into its white winter coat, with patches of brown and white fur.",
    'miststag': "A young deer stag with a clear deer face, four legs and tall antlers, its body pale silvery white and softly glowing like moonlit mist, the antlers frosted, gentle.",
}
